### ISSUE TITLE
SUGGESTION: Need player detection whitelist feature

### ISSUE THREAD

**Issue by chen125666** [DiffuseHyperion/InertiaAntiCheat#11]
Need player detection whitelist feature
Would like to add a player whitelist that allows players within the whitelist to bypass detection.
The reason is that the Replay Mod server side is not working properly, the Replay Mod server side recording feature is blocked by anti-cheat because Replay Mod is recorded through a minecraft account simulating a player entering the server
My English is not good, so I apologize in advance for any inappropriate expressions

**Comment by DiffuseHyperion** [comment]
Released version [0.0.6](https://modrinth.com/mod/inertiaanticheat/version/w5BW0kd7), which adds a permission called `inertiaanticheat.bypass`. This allows users to bypass mod checks/detection. Hopefully this works for you 👍
