### ISSUE TITLE
BUG: Not detecting  thats its on my client

### ISSUE THREAD

**Issue by RedsJack** [DiffuseHyperion/InertiaAntiCheat#12]
**Describe the bug**
While on server and client joining the server causes it to display a "you were kicked for not sending a response to intertia"
(same issue as previous report I saw but different person)
To Reproduce

**To Reproduce**
Steps to reproduce the problem:
1.I am using the mod through curseforge
2. Installed it both server and client side
3. Continues to give me error

**Expected behavior**
I join server
**Screenshots**
![image](https://github.com/DiffuseHyperion/InertiaAntiCheat/assets/139025669/89683e2a-a6df-44e5-81a7-28267a55727a)

**Server information (please complete the following information):**
 - Server software: Fabric
 - Server software loader version: (e.g. 0.14.21)
 - Minecraft version: (1.19.2)
 - Mod version: (0.0.6)
 - Fabric API version: (fabric-api-0.76.0+1.19.2)

**Mod config**
[InertiaAntiCheat.txt](https://github.com/DiffuseHyperion/InertiaAntiCheat/files/11994136/InertiaAntiCheat.txt)

**Additional context**
Here would also be the place where you put any other mods you were running when the problem occured.

**Comment by DiffuseHyperion** [comment]
Hey, can you try recreating this bug again with `debug = true` in both your server and client's config, and attach your logs here? Thanks!

For now, you can try increasing the graceTime to something higher if your connection to the server is particularly slow.

**Comment by RevMirin** [comment]
Same issue

**Comment by RiftSpatial** [comment]
This has been a reoccurring issue for my server for months, and I'm about to get rid of it, cause it causes issues with the auto download of the resource pack. This really needs to get fixed, so whenever you can, please look into it. Thank you.

**Comment by RiftSpatial** [comment]
[latest(Client).log](https://github.com/DiffuseHyperion/InertiaAntiCheat/files/12864448/latest.Client.log)
[latest(Server).log](https://github.com/DiffuseHyperion/InertiaAntiCheat/files/12864453/latest.Server.log)
Logs for when it just now happened.

**Comment by DiffuseHyperion** [comment]
Hey, sorry for the inactivity but a lot of things are happening irl for me for the past few months until now and I don't have enough time to invest into this mod. I'll try my best to come back to this when there is more time but for now I can't solve this issue, sorry

**Comment by DiffuseHyperion** [comment]
An update: i'm currently working on a new system for checking mods that should avoid this bug entirely. Slowly but steadily making progress on it

**Comment by DiffuseHyperion** [comment]
Closing this for now since this is on the alpha versions
