### ISSUE TITLE
Does this let "vanila" brand clients join

### ISSUE THREAD

**Issue by CuteistCat** [DiffuseHyperion/InertiaAntiCheat#15]
I might add this but i need this to be true for vanilla clients

**Comment by DiffuseHyperion** [comment]
Hi, i'm unable to work on this project atm, will look into this when I can. Thanks for reporting the bug :)

**Comment by CuteistCat** [comment]
i just realised meteor haz a spoof brand mudule

**Comment by DiffuseHyperion** [comment]
Not gonna lie I copy pasted my response when I saw this issue, my bad. Right now the mod doesn't check for brands from clients, and it's kind of outside the scope of the project. Might implement this in the future though

**Comment by CuteistCat** [comment]
yeah this sems like ts for modpack servers
