### ISSUE TITLE
SUGGESTION: Request for 1.20.1 on the newest mod version

### ISSUE THREAD

**Issue by 1Bulgarian** [DiffuseHyperion/InertiaAntiCheat#20]
**Is your feature request related to a problem? Please describe.**
I am an enjoyer of  your mod, but my server is working on 1.20.1 (FabricAPI 0.91.0) but with your latest couple of updates, I cannot update it anymore. 

**Describe the solution you'd like**
I am asking for the ability to use your mod in 1.20.1 (Fabric API 0.91.0).

**Comment by DiffuseHyperion** [comment]
Sorry for the late reply, unfortunately versions 1.0.0 won't work on Fabric API <0.93.0+1.20.4.

Although it is possible to port the fix in 0.93.0 to older versions, unfortunately the Fabric team has said that they do not intend to do so [here](https://github.com/FabricMC/fabric/pull/3495). I also can't justify the time to learn and patch this bug on X versions.

The alpha versions (<1.0.0) will work on older versions. I will try to push an update to those versions soon.

**Comment by DiffuseHyperion** [comment]
Also, it looks like the bug is gaining (some) traction from [here](https://github.com/FabricMC/fabric/issues/3624). Hopefully, Fabric backports this soon lol
