### ISSUE TITLE
UPDATE: Stable version for 1.20.1

### ISSUE THREAD

**Issue by Mrgaton** [DiffuseHyperion/InertiaAntiCheat#22]
that version i think is that the most mods has and would be great to be a stable version for it

**Comment by Mrgaton** [comment]
oh and add a anti speed hack like cheat engine that is very comnom

**Comment by Mrgaton** [comment]
and maybe a simple anti fly

**Comment by DiffuseHyperion** [comment]
> that version i think is that the most mods has and would be great to be a stable version for it

Unfortunately, it will be impossible to port the latest version for 1.20.1. The stable version requires a [fix](https://github.com/FabricMC/fabric/pull/3495) in Fabric API that is only on 1.20.4. In the same pull request, Fabric says that they do not plan backport this fix, so I can't really backport the latest version too.

Someone has asked for this backport in a separate [issue](https://github.com/FabricMC/fabric/issues/3624), hopefully it gets accepted lol

**Comment by DiffuseHyperion** [comment]
> oh and add a anti speed hack like cheat engine that is very comnom

> and maybe a simple anti fly

Sorry, but these anti cheats are kind of out of the scope of this project. Try installing another anti cheat mod for those functions
