### ISSUE TITLE
BUG: There is a conflict with MiniMOTD

### ISSUE THREAD

**Issue by Sakuraiina** [DiffuseHyperion/InertiaAntiCheat#32]
IntertiaAntiCheat change the MOTD which has already setted done with using MiniMOTD. Please add a option in the config to disable this function. Thanks.

**Comment by Sakuraiina** [comment]
![image](https://github.com/DiffuseHyperion/InertiaAntiCheat/assets/99549123/3789064e-1a05-480c-83de-3814576c5a06)

**Comment by DiffuseHyperion** [comment]
Sorry that it took a bit to implement this. Just released [version 1.0.2](https://github.com/DiffuseHyperion/InertiaAntiCheat/releases/tag/1.0.2), which should add this feature. Thanks for suggesting :)

**Comment by Sakuraiina** [comment]
I'm quite certain that the UI has disappeared, yet it still conflicts with the MiniMOTD. Please see the screenshot below.

![image](https://github.com/DiffuseHyperion/InertiaAntiCheat/assets/99549123/b0301c6a-9906-46cd-9fb4-591e9de029ce)
![image](https://github.com/DiffuseHyperion/InertiaAntiCheat/assets/99549123/fc39b8f1-5680-4d90-8ee0-08ea889e4c1d)

When I only add the MiniMOTD mod, it looks like this:
![image](https://github.com/DiffuseHyperion/InertiaAntiCheat/assets/99549123/77f5ff9f-680c-445e-b72c-2bfee2ca9b14)

**Comment by DiffuseHyperion** [comment]
Ohhh my bad, I understand what you mean now, looks like MiniMOTD uses stuff that this mod overrides. Will be working on a new version.

Also, the X ping indicator means that something went wrong when trying to ping the server, and thus none of the icons will show up. The ping seems to work on my computer, so it could be some random network issue.

**Comment by Sakuraiina** [comment]
When encountering the 'X ping' issue, I was using 127.0.0.1 (localhost) to connect to my local testing server. Perhaps there was an issue here. Thank you for your attention and response. Looking forward to the next version of this useful mod :)

**Comment by DiffuseHyperion** [comment]
Released [version 1.0.2.1](https://github.com/DiffuseHyperion/InertiaAntiCheat/releases/tag/1.0.2.1), which should fix this.
