### ISSUE TITLE
BUG: crashes on 1.20.6

### ISSUE THREAD

**Issue by nickademas** [DiffuseHyperion/InertiaAntiCheat#34]
**To Reproduce**
Steps to reproduce the problem:
1. Launch the game with this mod + fabric api on 1.20.6

[crash-2024-05-06_22.20.38-client.txt](https://github.com/DiffuseHyperion/InertiaAntiCheat/files/15226095/crash-2024-05-06_22.20.38-client.txt)
i used this version https://modrinth.com/mod/inertiaanticheat/version/0.0.7.2+1.20.2 idk if it's even supposed to be marked as 1.20.6 compatible

**Comment by rotgruengelb** [comment]
This appears to be because of an Incompatible version of Fabric API.

**Comment by DiffuseHyperion** [comment]
> This appears to be because of an Incompatible version of Fabric API.

Yup, this should be due to some update in Fabric API. Will need some time to see what changed and update accordingly.

**Comment by DiffuseHyperion** [comment]
Just a quick update: Mostly finished the update to 1.20.5 & 1.20.6, except there's a weird bug with a generic "Disconnected" message showing up when the mod kicks a player. I'm 75% sure that this is a bug with Fabric, but i'll push a release once this is fixed.

**Comment by DiffuseHyperion** [comment]
Sorry this took a while. For now, i've released version 0.0.8 which supports 1.20.5 and above. However, the above issue is still present, and thus i've "hid" the release away on Github for now.

The download is here: https://github.com/DiffuseHyperion/InertiaAntiCheat/releases/tag/0.0.8
