### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by DavidePgr** [DiffuseHyperion/InertiaAntiCheat#4]
Hi, I would love to use this mod... I'm creating a 1.20.1 server and it won't start because it's a 1.20 mod. I think it's an easy fix but I have no idea how to fix it because I have 0 knowledge about java. It would be awesome if you updated it! Thanks❤️

**Comment by rotgruengelb** [comment]
ill make a pull request

**Comment by DavidePgr** [comment]
> ill make a pull request

ok, thanks. then I would be able to download the .jar file to put in the mods folder in the server and clients?

**Comment by DavidePgr** [comment]
> [released version 0.0.3.1](https://modrinth.com/mod/inertiaanticheat/version/0.0.3.1), which should be compatible with minecraft 1.20.1. let me know if something goes wrong

Thank you so much, everything works perfectly!
