### ISSUE TITLE
BUG: Kicking players when joining the first time

### ISSUE THREAD

**Issue by yunus-cakir** [DiffuseHyperion/InertiaAntiCheat#40]
Hi! I installed and configured the Intertia Anti Cheat system in our 30 player SMP but it should have been secret. The players were installed the update that includes Intertia but they saw it they were joining the server first time. Could you help me that how can I fix that? I'd really appreciate it if you could help me.

**Screenshots**
![image](https://github.com/DiffuseHyperion/InertiaAntiCheat/assets/83448525/091c54de-b6ea-416a-8822-9d15368cf1f8)

**Server information (please complete the following information):**
 - Server software: Fabric
 - Server software loader version: 0.15.11
 - Minecraft version: 1.20.1
 - Mod version: 0.0.7.2
 - Fabric API version: (0.92.2+1.20.1)

**Mod config**
[InertiaAntiCheat.txt](https://github.com/user-attachments/files/15942830/InertiaAntiCheat.txt)
(Its .toml normally)

**Comment by DiffuseHyperion** [comment]
Sorry for the late reply, but I couldn't replicate this bug. Perhaps try increasing `delay` in your server's config and see if it helps.
