### ISSUE TITLE
SUGGESTION: Revert Hashes

### ISSUE THREAD

**Issue by Tunga-Tech** [DiffuseHyperion/InertiaAntiCheat#44]
I was wondering if you would be able to make it so you can either see the player's modlist or possibly add a function on the website to revert the hashes.

**Comment by DiffuseHyperion** [comment]
Sorry for the super late response, but for modern versions, the server never receives the name of the mods the clients are using, only the data of the mod. 

You could try to identify the mod from the hash generated, but as Misha4ek said, it would require having a database of every single version of every single mod to be able to identify it.

Unfortunately, this can't work with how the mod communicates as of now. Hope you understand :)
