### ISSUE TITLE
SUGGESTION: 1.21.1 support

### ISSUE THREAD

**Issue by meo209** [DiffuseHyperion/InertiaAntiCheat#47]
**Is your feature request related to a problem? Please describe.**
IAC does not currently work on 1.21.1 from my testing.

**Describe the solution you'd like**
I'd like to have an update for 1.21.1 for the InertiaAntiCheat mod.

**Comment by Yoon0117** [comment]
what does it say? the error message

**Comment by Yoon0117** [comment]
I'm having an issue as well, it doesn't work at all. Also, if I have a server 1.21.1 and client 1.20.1 with ViaFabricPlus, will the AC work as intended?

**Comment by DiffuseHyperion** [comment]
Right now, the mod doesn't support 1.21. I'll try to update it when I can

**Comment by DiffuseHyperion** [comment]
Just released version [1.0.3.1](https://modrinth.com/mod/inertiaanticheat/version/1.0.3.1), which should now have 1.21.1 support.
