### ISSUE TITLE
SUGGESTION: Whitelist improvement

### ISSUE THREAD

**Issue by SamuelNT** [DiffuseHyperion/InertiaAntiCheat#6]
I would like it to be possible to have a list of mods allowed but not forced on the server while blocking all other mods. Kind of like a mix between the hash mode and the whitelist mode.  For example a server with a modpack can have players with client mods such as Xaeros Worldmap while other players use voxels map. What I want is for both to be allowed but neither required.

**Comment by rotgruengelb** [comment]
Yea, that was something I would have suggested too.
Would be very neat and make the Mod overall way more useful.

**Comment by DiffuseHyperion** [comment]
alright, ill think of something :)

**Comment by DiffuseHyperion** [comment]
Released version [0.0.5](https://github.com/DiffuseHyperion/InertiaAntiCheat/releases/tag/0.0.5), look in the release description for more details. Hope this solves your issue, let me know if something goes wrong 👍

**Comment by RevMirin** [comment]
user hash is constantly changing, which hash should be inserted in this case
